openapi: 3.1.0
info:
  title: PulTime User Service API
  version: 1.0.0

paths:
  /user/{id}:
    patch:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: ID pengguna yang ingin diupdate
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/user-schema.yaml#/components/schemas/UpdateUserRequest'
      responses:
        200:
          description: Berhasil update pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/user-schema.yaml#/components/schemas/GetUserByIdResponse'
        400:
          description: Gagal update pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/error-schema.yaml#/components/schemas/ErrorResponse'

    delete:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: ID pengguna yang ingin dihapus
          schema:
            type: string
      responses:
        200:
          description: Berhasil menghapus pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/user-schema.yaml#/components/schemas/GetUserByIdResponse'
        400:
          description: Gagal menghapus pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/error-schema.yaml#/components/schemas/ErrorResponse'

    get:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: ID pengguna yang ingin diambil
          schema:
            type: string
      responses:
        200:
          description: Berhasil mengambil data pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/user-schema.yaml#/components/schemas/GetUserByIdResponse'
        400:
          description: Gagal mengambil data pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/error-schema.yaml#/components/schemas/ErrorResponse'

  /user/{id}/classes:
    get:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: ID pengguna yang ingin diambil
          schema:
            type: string
      responses:
        200:
          description: Berhasil mengambil data kelas pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/user-schema.yaml#/components/schemas/GetUserClassesResponse'
        400:
          description: Gagal mengambil data kelas pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/error-schema.yaml#/components/schemas/ErrorResponse'

  /user/{id}/teams:
    get:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: ID pengguna yang ingin diambil
          schema:
            type: string
      responses:
        200:
          description: Berhasil mengambil data tim pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/user-schema.yaml#/components/schemas/GetUserTeamsResponse'
        400:
          description: Gagal mengambil data tim pengguna
          content:
            application/json:
              schema:
                $ref: '../schemas/error-schema.yaml#/components/schemas/ErrorResponse'
